// Central mock dataset for «دیدبان حسابرسی» — phase 1 demo.
// Everything is deterministic so citations & IDs stay consistent across pages.

import type {
  AccountingDocument,
  AnomalySignal,
  Attachment,
  AuditFinding,
  AuditTrailEntry,
  ComplianceRule,
  ComplianceRuleVersion,
  DashboardMetrics,
  EvidenceRequirement,
  KnowledgeChunk,
  KnowledgeCitation,
  KnowledgeSource,
  MatchingChain,
  User,
  Vendor,
} from "@/types/domain";

// ---------------- Users ----------------
export const mockUser: User = {
  id: "u-1",
  username: "auditor",
  fullName: "علی محمدی",
  role: "auditor",
};

// ---------------- Vendors ----------------
export const vendors: Vendor[] = [
  {
    id: "v-golestan",
    name: "گلستان پارس",
    nationalId: "۱۰۱۰۲۳۴۵۶۷۸",
    category: "خدمات و کالای تشریفاتی",
    riskScore: 78,
    totalPurchase: 6_800_000_000,
    activeContracts: 2,
    signals: [
      {
        id: "vr-1",
        vendorId: "v-golestan",
        label: "افزایش ناگهانی حجم فاکتور در ۹۰ روز اخیر",
        severity: "high",
        detectedAt: "۱۴۰۵/۰۴/۱۰",
      },
      {
        id: "vr-2",
        vendorId: "v-golestan",
        label: "الگوی مبالغ رند در ۳ سند اخیر",
        severity: "medium",
        detectedAt: "۱۴۰۵/۰۴/۰۵",
      },
    ],
  },
  {
    id: "v-parsian-it",
    name: "پارسیان فناوری",
    nationalId: "۱۰۱۰۹۸۷۶۵۴۳",
    category: "تجهیزات فناوری اطلاعات",
    riskScore: 32,
    totalPurchase: 3_200_000_000,
    activeContracts: 1,
    signals: [],
  },
  {
    id: "v-arya-service",
    name: "خدمات فنی آریا",
    nationalId: "۱۰۱۰۵۵۵۶۶۷۷",
    category: "خدمات پیمانکاری",
    riskScore: 61,
    totalPurchase: 12_400_000_000,
    activeContracts: 4,
    signals: [
      {
        id: "vr-3",
        vendorId: "v-arya-service",
        label: "قرارداد بدون مفاصاحساب بیمه",
        severity: "high",
        detectedAt: "۱۴۰۵/۰۳/۲۰",
      },
    ],
  },
];

// ---------------- Knowledge Base ----------------
export const knowledgeSources: KnowledgeSource[] = [
  {
    id: "ks-direct-tax",
    title: "قانون مالیات‌های مستقیم",
    publisher: "سازمان امور مالیاتی کشور",
    category: "tax",
    versionLabel: "اصلاحیه ۱۴۰۴",
    effectiveFrom: "۱۴۰۴/۰۱/۰۱",
    pageCount: 312,
    status: "active",
    chunkCount: 1240,
    lastProcessedAt: "۱۴۰۵/۰۲/۱۰",
  },
  {
    id: "ks-vat",
    title: "قانون مالیات بر ارزش افزوده و سامانه مؤدیان",
    publisher: "سازمان امور مالیاتی کشور",
    category: "tax",
    versionLabel: "نسخه ۱۴۰۴",
    effectiveFrom: "۱۴۰۴/۰۱/۰۱",
    pageCount: 96,
    status: "active",
    chunkCount: 420,
    lastProcessedAt: "۱۴۰۵/۰۲/۱۲",
  },
  {
    id: "ks-social-security",
    title: "قانون تأمین اجتماعی",
    publisher: "سازمان تأمین اجتماعی",
    category: "insurance",
    versionLabel: "اصلاحیه ۱۳۹۶",
    effectiveFrom: "۱۳۹۶/۰۵/۱۰",
    pageCount: 210,
    status: "active",
    chunkCount: 680,
    lastProcessedAt: "۱۴۰۵/۰۱/۱۵",
  },
  {
    id: "ks-acc-std",
    title: "استانداردهای حسابداری ایران",
    publisher: "سازمان حسابرسی",
    category: "accountingStandard",
    versionLabel: "چاپ ۱۴۰۳",
    effectiveFrom: "۱۴۰۳/۰۱/۰۱",
    pageCount: 540,
    status: "active",
    chunkCount: 2100,
    lastProcessedAt: "۱۴۰۵/۰۲/۰۱",
  },
  {
    id: "ks-audit-std",
    title: "استانداردهای حسابرسی ایران",
    publisher: "سازمان حسابرسی",
    category: "auditingStandard",
    versionLabel: "نسخه ۱۴۰۲",
    effectiveFrom: "۱۴۰۲/۰۱/۰۱",
    pageCount: 480,
    status: "active",
    chunkCount: 1850,
    lastProcessedAt: "۱۴۰۵/۰۱/۲۰",
  },
  {
    id: "ks-internal-procurement",
    title: "آیین‌نامه معاملات داخلی شرکت",
    publisher: "هیئت مدیره — شرکت پرشیا",
    category: "internal",
    versionLabel: "v3 — بازنگری ۱۴۰۴/۱۰",
    effectiveFrom: "۱۴۰۴/۱۰/۰۱",
    pageCount: 42,
    status: "active",
    chunkCount: 180,
    lastProcessedAt: "۱۴۰۵/۰۳/۰۱",
  },
];

export const knowledgeChunks: KnowledgeChunk[] = [
  {
    id: "kc-vat-19",
    sourceId: "ks-vat",
    articleNumber: "۱۹",
    pageNumber: 24,
    text:
      "کلیه مؤدیان مکلفند صورتحساب الکترونیکی معتبر با شماره منحصربه‌فرد مالیاتی صادر و در سامانه مؤدیان ثبت نمایند. عدم تأیید صورتحساب توسط خریدار موجب سلب اعتبار صورتحساب می‌گردد.",
  },
  {
    id: "kc-ss-38",
    sourceId: "ks-social-security",
    articleNumber: "۳۸",
    pageNumber: 61,
    text:
      "در قراردادهای پیمانکاری، واگذارنده کار مکلف است تا زمان دریافت مفاصاحساب بیمه، از پرداخت آخرین قسط پیمانکار خودداری نماید. این ماده صرفاً به قراردادهای پیمانکاری اطلاق می‌شود.",
  },
  {
    id: "kc-internal-12",
    sourceId: "ks-internal-procurement",
    articleNumber: "۱۲",
    clauseNumber: "بند ۲",
    pageNumber: 8,
    text:
      "سقف خرید مستقیم بدون برگزاری فرآیند استعلام رقابتی، مبلغ ۱٬۵۰۰٬۰۰۰٬۰۰۰ ریال است. خریدهای بالاتر از این سقف نیازمند حداقل سه استعلام رسمی و تصویب کمیته معاملات است.",
  },
  {
    id: "kc-acc-8",
    sourceId: "ks-acc-std",
    articleNumber: "استاندارد ۸",
    clauseNumber: "بند ۱۴",
    pageNumber: 132,
    text:
      "هزینه‌های عملیاتی باید در دوره‌ای که خدمت یا کالای مربوطه مصرف شده است شناسایی و در سرفصل مناسب طبقه‌بندی گردد.",
  },
  {
    id: "kc-audit-500",
    sourceId: "ks-audit-std",
    articleNumber: "استاندارد ۵۰۰",
    clauseNumber: "بند ۶",
    pageNumber: 88,
    text:
      "شواهد حسابرسی باید از نظر کفایت (کمّیت) و مناسب‌بودن (کیفیت و ارتباط) کافی باشند تا حسابرس بتواند اظهارنظر متکی بر آن ارائه دهد. قابلیت اتکای شواهد به منبع، ماهیت و شرایط تحصیل آن‌ها بستگی دارد.",
  },
];

export const citations: KnowledgeCitation[] = [
  {
    id: "ct-vat-19",
    sourceId: "ks-vat",
    sourceTitle: "قانون مالیات بر ارزش افزوده و سامانه مؤدیان",
    publisher: "سازمان امور مالیاتی کشور",
    articleNumber: "۱۹",
    pageNumber: 24,
    versionLabel: "نسخه ۱۴۰۴",
    effectiveFrom: "۱۴۰۴/۰۱/۰۱",
    snippet: knowledgeChunks[0].text,
  },
  {
    id: "ct-ss-38",
    sourceId: "ks-social-security",
    sourceTitle: "قانون تأمین اجتماعی",
    publisher: "سازمان تأمین اجتماعی",
    articleNumber: "۳۸",
    pageNumber: 61,
    versionLabel: "اصلاحیه ۱۳۹۶",
    effectiveFrom: "۱۳۹۶/۰۵/۱۰",
    snippet: knowledgeChunks[1].text,
  },
  {
    id: "ct-internal-12",
    sourceId: "ks-internal-procurement",
    sourceTitle: "آیین‌نامه معاملات داخلی شرکت",
    publisher: "هیئت مدیره — شرکت پرشیا",
    articleNumber: "۱۲",
    clauseNumber: "بند ۲",
    pageNumber: 8,
    versionLabel: "v3 — بازنگری ۱۴۰۴/۱۰",
    effectiveFrom: "۱۴۰۴/۱۰/۰۱",
    snippet: knowledgeChunks[2].text,
  },
  {
    id: "ct-acc-8",
    sourceId: "ks-acc-std",
    sourceTitle: "استانداردهای حسابداری ایران",
    publisher: "سازمان حسابرسی",
    articleNumber: "استاندارد ۸",
    clauseNumber: "بند ۱۴",
    pageNumber: 132,
    versionLabel: "چاپ ۱۴۰۳",
    effectiveFrom: "۱۴۰۳/۰۱/۰۱",
    snippet: knowledgeChunks[3].text,
  },
  {
    id: "ct-audit-500",
    sourceId: "ks-audit-std",
    sourceTitle: "استانداردهای حسابرسی ایران",
    publisher: "سازمان حسابرسی",
    articleNumber: "استاندارد ۵۰۰",
    clauseNumber: "بند ۶",
    pageNumber: 88,
    versionLabel: "نسخه ۱۴۰۲",
    effectiveFrom: "۱۴۰۲/۰۱/۰۱",
    snippet: knowledgeChunks[4].text,
  },
];

// ---------------- Compliance Rules ----------------
export const complianceRules: ComplianceRule[] = [
  {
    id: "r-vat-einvoice",
    title: "اعتبار صورتحساب الکترونیکی در سامانه مؤدیان",
    description:
      "صورتحساب الکترونیکی معتبر با شماره منحصربه‌فرد مالیاتی باید در سامانه مؤدیان یافت شده و توسط خریدار تأیید شده باشد.",
    category: "tax",
    appliesToKinds: ["goodsPurchase", "servicePurchase", "contract"],
    active: true,
    scope: "documentControl",
    currentVersionId: "rv-vat-einvoice-1404",
  },
  {
    id: "r-ss-38",
    title: "مفاصاحساب بیمه پیمانکار (ماده ۳۸ تأمین اجتماعی)",
    description:
      "در قراردادهای پیمانکاری، دریافت مفاصاحساب بیمه پیش از پرداخت آخرین قسط الزامی است. صرفاً برای قرارداد پیمانکاری کاربرد دارد.",
    category: "insurance",
    appliesToKinds: ["contract", "servicePurchase"],
    active: true,
    scope: "documentControl",
    currentVersionId: "rv-ss-38-1396",
  },
  {
    id: "r-internal-cap",
    title: "سقف خرید مستقیم بدون استعلام رقابتی",
    description: "مبالغ بالای ۱٬۵۰۰٬۰۰۰٬۰۰۰ ریال باید از طریق استعلام رقابتی انجام شود.",
    category: "internalControl",
    appliesToKinds: ["goodsPurchase", "servicePurchase", "contract"],
    amountThreshold: 1_500_000_000,
    active: true,
    scope: "documentControl",
    currentVersionId: "rv-internal-cap-v3",
  },
  {
    id: "r-acc-8",
    title: "طبقه‌بندی صحیح هزینه‌های عملیاتی (استاندارد ۸)",
    description: "شناسایی و طبقه‌بندی هزینه در سرفصل مناسب و دوره صحیح.",
    category: "accountingStandard",
    appliesToKinds: ["goodsPurchase", "servicePurchase", "contract", "other"],
    active: true,
    scope: "documentControl",
    currentVersionId: "rv-acc-8-1403",
  },
  {
    id: "r-audit-500",
    title: "کفایت و قابلیت اتکای شواهد (استاندارد حسابرسی ۵۰۰)",
    description: "ارزیابی حسابرس نسبت به کفایت، مناسب‌بودن و قابلیت اتکای شواهد گردآوری‌شده.",
    category: "auditingStandard",
    appliesToKinds: ["goodsPurchase", "servicePurchase", "contract", "other"],
    active: true,
    scope: "auditorEvaluation",
    currentVersionId: "rv-audit-500-1402",
  },
];

export const ruleVersions: ComplianceRuleVersion[] = [
  {
    id: "rv-vat-einvoice-1404",
    ruleId: "r-vat-einvoice",
    versionLabel: "نسخه ۱۴۰۴",
    effectiveFrom: "۱۴۰۴/۰۱/۰۱",
    sourceId: "ks-vat",
    articleNumber: "۱۹",
    pageNumber: 24,
  },
  {
    id: "rv-ss-38-1396",
    ruleId: "r-ss-38",
    versionLabel: "اصلاحیه ۱۳۹۶",
    effectiveFrom: "۱۳۹۶/۰۵/۱۰",
    sourceId: "ks-social-security",
    articleNumber: "۳۸",
    pageNumber: 61,
  },
  {
    id: "rv-internal-cap-v3",
    ruleId: "r-internal-cap",
    versionLabel: "v3 — ۱۴۰۴/۱۰",
    effectiveFrom: "۱۴۰۴/۱۰/۰۱",
    sourceId: "ks-internal-procurement",
    articleNumber: "۱۲",
    clauseNumber: "بند ۲",
    pageNumber: 8,
  },
  {
    id: "rv-acc-8-1403",
    ruleId: "r-acc-8",
    versionLabel: "چاپ ۱۴۰۳",
    effectiveFrom: "۱۴۰۳/۰۱/۰۱",
    sourceId: "ks-acc-std",
    articleNumber: "استاندارد ۸",
    clauseNumber: "بند ۱۴",
    pageNumber: 132,
  },
  {
    id: "rv-audit-500-1402",
    ruleId: "r-audit-500",
    versionLabel: "نسخه ۱۴۰۲",
    effectiveFrom: "۱۴۰۲/۰۱/۰۱",
    sourceId: "ks-audit-std",
    articleNumber: "استاندارد ۵۰۰",
    clauseNumber: "بند ۶",
    pageNumber: 88,
  },
];

// ---------------- Documents ----------------
export const documents: AccountingDocument[] = [
  {
    id: "d-flower-1405",
    number: "SND-۱۴۰۵-۰۰۴۲۱",
    date: "۱۴۰۵/۰۴/۱۵",
    isoDate: "2026-07-06",
    title: "خرید ۴۰۰ شاخه گل رز طبیعی برای مراسم افتتاحیه",
    description: "هزینه گل‌آرایی مراسم سالانه — واحد روابط عمومی",
    amount: 2_400_000_000,
    vendorId: "v-golestan",
    organizationUnit: "روابط عمومی",
    documentType: "سند هزینه",
    transactionKind: "goodsPurchase",
    riskScore: 87,
    status: "needsReview",
    assignee: "علی محمدی",
    lines: [
      {
        id: "jl-1",
        account: "هزینه‌های تبلیغات و روابط عمومی",
        accountCode: "۷۱۲۰۴",
        debit: 2_400_000_000,
        credit: 0,
        description: "خرید گل رز طبیعی — گلستان پارس",
      },
      {
        id: "jl-2",
        account: "حساب‌های پرداختنی تجاری",
        accountCode: "۲۱۰۰۱",
        debit: 0,
        credit: 2_400_000_000,
        description: "بستانکار فروشنده",
      },
    ],
    createdAt: "۱۴۰۵/۰۴/۱۶ ۰۹:۲۲",
  },
  {
    id: "d-flower-contract",
    number: "SND-۱۴۰۵-۰۰۴۲۲",
    date: "۱۴۰۵/۰۴/۱۸",
    isoDate: "2026-07-09",
    title: "قرارداد تأمین، طراحی و اجرای گل‌آرایی مراسم",
    description: "قرارداد پیمانکاری خدمات گل‌آرایی سالن اصلی",
    amount: 4_200_000_000,
    vendorId: "v-golestan",
    organizationUnit: "روابط عمومی",
    documentType: "سند هزینه",
    transactionKind: "contract",
    riskScore: 64,
    status: "needsReview",
    assignee: "علی محمدی",
    lines: [],
    createdAt: "۱۴۰۵/۰۴/۱۹ ۱۰:۰۴",
  },
  {
    id: "d-laptop-1405",
    number: "SND-۱۴۰۵-۰۰۳۸۹",
    date: "۱۴۰۵/۰۴/۰۲",
    isoDate: "2026-06-23",
    title: "خرید ۱۰ دستگاه لپ‌تاپ کارشناسی",
    description: "تجهیز واحد فناوری اطلاعات",
    amount: 1_180_000_000,
    vendorId: "v-parsian-it",
    organizationUnit: "فناوری اطلاعات",
    documentType: "سند هزینه",
    transactionKind: "goodsPurchase",
    riskScore: 22,
    status: "approved",
    assignee: "علی محمدی",
    lines: [],
    createdAt: "۱۴۰۵/۰۴/۰۳ ۱۴:۱۰",
  },
  {
    id: "d-maintenance-1405",
    number: "SND-۱۴۰۵-۰۰۴۱۰",
    date: "۱۴۰۵/۰۴/۱۰",
    isoDate: "2026-07-01",
    title: "خدمات تعمیر و نگهداری تأسیسات ساختمان مرکزی",
    description: "پیمان سه‌ماهه خدمات فنی",
    amount: 3_600_000_000,
    vendorId: "v-arya-service",
    organizationUnit: "پشتیبانی",
    documentType: "سند هزینه",
    transactionKind: "servicePurchase",
    riskScore: 58,
    status: "legalIssue",
    assignee: "علی محمدی",
    lines: [],
    createdAt: "۱۴۰۵/۰۴/۱۱ ۰۸:۴۰",
  },
];

// ---------------- Evidence ----------------
export const evidenceRequirements: EvidenceRequirement[] = [
  {
    id: "er-pr",
    kind: "purchaseRequest",
    title: "درخواست خرید",
    mandatory: true,
    rationale: "شواهد آغاز فرآیند خرید و تأیید نیاز واحد درخواست‌کننده.",
  },
  {
    id: "er-approval",
    kind: "purchaseApproval",
    title: "مجوز خرید",
    mandatory: true,
    rationale: "تأیید مقام مجاز بر اساس آیین‌نامه معاملات داخلی.",
  },
  {
    id: "er-inquiry",
    kind: "priceInquiry",
    title: "استعلام قیمت",
    mandatory: true,
    rationale: "الزام برای خریدهای بالای سقف مستقیم.",
  },
  {
    id: "er-po",
    kind: "purchaseOrder",
    title: "سفارش خرید",
    mandatory: true,
    rationale: "توافق رسمی با فروشنده.",
  },
  {
    id: "er-invoice",
    kind: "eInvoice",
    title: "صورتحساب الکترونیکی معتبر",
    mandatory: true,
    rationale: "الزام قانون م.ب.ا.ک و سامانه مؤدیان.",
  },
  {
    id: "er-receipt",
    kind: "goodsReceipt",
    title: "رسید انبار / تحویل کالا",
    mandatory: true,
    rationale: "اثبات دریافت کالا یا خدمت.",
  },
];

export const attachments: Attachment[] = [
  {
    id: "att-flower-pr",
    documentId: "d-flower-1405",
    filename: "درخواست_خرید_۱۴۰۵-۰۷۸.pdf",
    fileType: "pdf",
    size: 218_000,
    uploadedAt: "۱۴۰۵/۰۴/۱۶ ۰۹:۲۰",
    ocrConfidence: 0.94,
    relevanceScore: 0.91,
    detectedKind: "purchaseRequest",
    extractedSummary: "درخواست خرید گل رز طبیعی توسط واحد روابط عمومی — تعداد ۴۰۰ شاخه",
  },
  {
    id: "att-flower-approval",
    documentId: "d-flower-1405",
    filename: "مجوز_مدیرعامل.jpg",
    fileType: "image",
    size: 420_000,
    uploadedAt: "۱۴۰۵/۰۴/۱۶ ۰۹:۲۱",
    ocrConfidence: 0.72,
    relevanceScore: 0.68,
    detectedKind: "purchaseApproval",
    extractedSummary: "مجوز خرید تشریفاتی — امضای مدیرعامل",
  },
  {
    id: "att-flower-invoice",
    documentId: "d-flower-1405",
    filename: "فاکتور_۱۴۰۵.pdf",
    fileType: "pdf",
    size: 512_000,
    uploadedAt: "۱۴۰۵/۰۴/۱۶ ۰۹:۲۲",
    ocrConfidence: 0.88,
    relevanceScore: 0.21,
    detectedKind: "invoice",
    extractedSummary:
      "⚠️ محتوای فاکتور شامل اقلام «لپ‌تاپ ایسوس» است، نه گل. ارتباط معنایی با سند حسابداری ضعیف است.",
  },
  {
    id: "att-flower-receipt",
    documentId: "d-flower-1405",
    filename: "رسید_تحویل.pdf",
    fileType: "pdf",
    size: 180_000,
    uploadedAt: "۱۴۰۵/۰۴/۱۶ ۰۹:۲۳",
    ocrConfidence: 0.83,
    relevanceScore: 0.77,
    detectedKind: "goodsReceipt",
    extractedSummary: "رسید تحویل ۴۰۰ شاخه گل — امضای مسئول تشریفات",
  },
];

// ---------------- Anomalies ----------------
export const anomalies: AnomalySignal[] = [
  {
    id: "an-flower-price",
    documentId: "d-flower-1405",
    kind: "price",
    severity: "high",
    description: "قیمت واحد شاخه گل ۶ میلیون ریال، بسیار بالاتر از میانگین داخلی و بازار",
    benchmark: {
      documentAmount: 2_400_000_000,
      internalAverage: 850_000_000,
      internalSampleSize: 6,
      marketMin: 900_000_000,
      marketMax: 1_100_000_000,
      deviationPercent: 182,
    },
  },
];

// ---------------- Matching Chain ----------------
export const matchingChains: Record<string, MatchingChain> = {
  "d-flower-1405": {
    documentId: "d-flower-1405",
    nodes: [
      {
        id: "mn-1",
        kind: "purchaseRequest",
        label: "درخواست خرید",
        reference: "PR-۱۴۰۵-۰۷۸",
        date: "۱۴۰۵/۰۴/۱۲",
        status: "present",
      },
      {
        id: "mn-2",
        kind: "priceInquiry",
        label: "استعلام قیمت",
        status: "missing",
        note: "برای مبالغ بالای سقف مستقیم الزامی است",
      },
      {
        id: "mn-3",
        kind: "purchaseOrder",
        label: "سفارش خرید",
        reference: "PO-۱۴۰۵-۱۰۹",
        date: "۱۴۰۵/۰۴/۱۳",
        status: "present",
      },
      {
        id: "mn-4",
        kind: "goodsReceipt",
        label: "رسید تحویل",
        reference: "GR-۱۴۰۵-۲۱۴",
        date: "۱۴۰۵/۰۴/۱۵",
        status: "present",
      },
      {
        id: "mn-5",
        kind: "invoice",
        label: "فاکتور فروشنده",
        reference: "INV-۱۴۰۵-۵۵۱",
        status: "mismatch",
        note: "محتوای فاکتور با سند مطابقت ندارد (اقلام لپ‌تاپ)",
      },
      {
        id: "mn-6",
        kind: "accountingDocument",
        label: "سند حسابداری",
        reference: "SND-۱۴۰۵-۰۰۴۲۱",
        date: "۱۴۰۵/۰۴/۱۶",
        status: "present",
      },
      {
        id: "mn-7",
        kind: "bankPayment",
        label: "پرداخت بانکی",
        status: "missing",
        note: "پرداخت هنوز ثبت نشده است",
      },
    ],
  },
};

// ---------------- Findings ----------------
export const initialFindings: AuditFinding[] = [];

// ---------------- Audit Trail (seed) ----------------
export const seedAuditTrail: AuditTrailEntry[] = [
  {
    id: "at-seed-1",
    entityId: "d-flower-1405",
    entityKind: "document",
    actor: "سیستم",
    action: "ثبت سند در سامانه",
    timestamp: "۱۴۰۵/۰۴/۱۶ ۰۹:۲۲",
  },
  {
    id: "at-seed-2",
    entityId: "d-flower-1405",
    entityKind: "document",
    actor: "علی محمدی",
    action: "تخصیص به حسابرس",
    timestamp: "۱۴۰۵/۰۴/۱۶ ۱۰:۰۰",
  },
];

// ---------------- Dashboard ----------------
export const dashboardMetrics: DashboardMetrics = {
  documentsReviewed: 1284,
  highRiskDocuments: 47,
  incompleteEvidence: 62,
  legalIssues: 21,
  accountingIssues: 14,
  amountAtRisk: 128_400_000_000,
  openFindings: 34,
  resolvedFindings: 118,
  coveragePercent: 82,
  riskTrend: [
    { period: "بهمن", score: 42 },
    { period: "اسفند", score: 51 },
    { period: "فروردین", score: 48 },
    { period: "اردیبهشت", score: 57 },
    { period: "خرداد", score: 63 },
    { period: "تیر", score: 71 },
  ],
  findingsBySeverity: [
    { severity: "بحرانی", count: 6 },
    { severity: "بالا", count: 18 },
    { severity: "متوسط", count: 22 },
    { severity: "پایین", count: 12 },
  ],
  findingsByCategory: [
    { category: "مالیات", count: 15 },
    { category: "بیمه", count: 9 },
    { category: "استانداردهای حسابداری", count: 8 },
    { category: "کنترل داخلی", count: 14 },
    { category: "ناهنجاری قیمت", count: 12 },
  ],
};

// ---------------- Users (Phase 3) ----------------
import type {
  ExecutiveKPIs,
  SystemSettings,
  VendorConflictAlert,
  VendorTransactionEntry,
} from "@/types/domain";

export const users: User[] = [
  {
    id: "u-1",
    username: "auditor",
    fullName: "علی محمدی",
    role: "auditor",
    email: "a.mohammadi@persia.co",
    status: "active",
    lastActiveAt: "۱۴۰۵/۰۴/۲۰ ۰۹:۴۲",
    permissions: ["documents.view", "findings.edit", "reports.export"],
  },
  {
    id: "u-2",
    username: "manager",
    fullName: "فاطمه آزاد",
    role: "manager",
    email: "n.rezaei@persia.co",
    status: "active",
    lastActiveAt: "۱۴۰۵/۰۴/۱۹ ۱۶:۱۰",
    permissions: ["findings.approve", "reports.view", "kpi.view"],
  },
  {
    id: "u-3",
    username: "admin",
    fullName: "کامران عبدی",
    role: "admin",
    email: "h.karimi@persia.co",
    status: "active",
    lastActiveAt: "۱۴۰۵/۰۴/۲۰ ۰۸:۰۰",
    permissions: ["*"],
  },
  {
    id: "u-4",
    username: "s.ahmadi",
    fullName: "سارا احمدی",
    role: "auditor",
    email: "s.ahmadi@persia.co",
    status: "invited",
    lastActiveAt: "—",
    permissions: ["documents.view", "findings.edit"],
  },
  {
    id: "u-5",
    username: "r.tabatabaei",
    fullName: "رضا طباطبایی",
    role: "auditor",
    email: "r.tabatabaei@persia.co",
    status: "disabled",
    lastActiveAt: "۱۴۰۵/۰۲/۰۵ ۱۱:۲۰",
    permissions: ["documents.view"],
  },
];

// ---------------- System Settings ----------------
export const defaultSettings: SystemSettings = {
  organizationName: "شرکت پرشیا",
  fiscalYear: "۱۴۰۵",
  currency: "IRR",
  language: "fa",
  timezone: "Asia/Tehran",
  risk: { lowMax: 39, mediumMax: 69, autoDismissBelow: 10 },
  ai: {
    model: "google/gemini-2.5-flash",
    temperature: 0.2,
    minConfidence: 0.7,
    useHybrid: true,
  },
  notifications: {
    emailOnNewFinding: true,
    emailOnHighRisk: true,
    digestFrequency: "daily",
  },
  directPurchaseCap: 1_500_000_000,
};

// ---------------- Vendor Transactions & Conflicts ----------------
export const vendorTransactions: VendorTransactionEntry[] = [
  {
    id: "vt-1",
    vendorId: "v-golestan",
    date: "۱۴۰۵/۰۴/۱۵",
    documentNumber: "AP-1405-0421",
    documentId: "d-flower-1405",
    amount: 2_400_000_000,
    kind: "خرید تشریفاتی",
    riskScore: 87,
  },
  {
    id: "vt-2",
    vendorId: "v-golestan",
    date: "۱۴۰۵/۰۳/۲۸",
    documentNumber: "AP-1405-0388",
    amount: 1_900_000_000,
    kind: "خرید تشریفاتی",
    riskScore: 72,
  },
  {
    id: "vt-3",
    vendorId: "v-golestan",
    date: "۱۴۰۵/۰۳/۱۰",
    documentNumber: "AP-1405-0341",
    amount: 1_500_000_000,
    kind: "خرید تشریفاتی",
    riskScore: 55,
  },
  {
    id: "vt-4",
    vendorId: "v-golestan",
    date: "۱۴۰۵/۰۲/۲۲",
    documentNumber: "AP-1405-0272",
    amount: 1_000_000_000,
    kind: "خرید تشریفاتی",
    riskScore: 30,
  },
  {
    id: "vt-5",
    vendorId: "v-parsian-it",
    date: "۱۴۰۵/۰۴/۱۰",
    documentNumber: "AP-1405-0402",
    amount: 3_200_000_000,
    kind: "خرید تجهیزات",
    riskScore: 32,
  },
  {
    id: "vt-6",
    vendorId: "v-arya-service",
    date: "۱۴۰۵/۰۴/۰۵",
    documentNumber: "AP-1405-0395",
    amount: 4_800_000_000,
    kind: "خدمات پیمانکاری",
    riskScore: 68,
  },
  {
    id: "vt-7",
    vendorId: "v-arya-service",
    date: "۱۴۰۵/۰۳/۱۵",
    documentNumber: "AP-1405-0352",
    amount: 3_600_000_000,
    kind: "خدمات پیمانکاری",
    riskScore: 61,
  },
];

export const vendorConflicts: VendorConflictAlert[] = [
  {
    id: "vc-1",
    vendorId: "v-golestan",
    label: "ارتباط سهامداری با کارمند واحد تدارکات",
    severity: "high",
    detail: "شناسه ملی سهامدار با کارمند «م. رحیمی» در واحد تدارکات مطابقت دارد.",
  },
  {
    id: "vc-2",
    vendorId: "v-arya-service",
    label: "آدرس مشابه با یک تأمین‌کننده دیگر",
    severity: "medium",
    detail: "آدرس ثبت‌شده با تأمین‌کننده «الوند صنعت» یکسان است.",
  },
];

// ---------------- Executive KPIs ----------------
export const executiveKPIs: ExecutiveKPIs = {
  totalDocuments: 128,
  totalAmountReviewed: 84_300_000_000,
  amountAtRisk: 11_700_000_000,
  controlCoverage: 78,
  avgTimeToClose: 4.6,
  slaCompliance: 82,
  openFindings: 17,
  overdueFindings: 4,
  suggestedFindings: 9,
  approvedFindings: 22,
  riskTrend: [
    { period: "فروردین", score: 42 },
    { period: "اردیبهشت", score: 48 },
    { period: "خرداد", score: 55 },
    { period: "تیر", score: 63 },
  ],
  categoryBreakdown: [
    { category: "مالیاتی", count: 12, amount: 5_400_000_000 },
    { category: "بیمه‌ای", count: 6, amount: 2_100_000_000 },
    { category: "کنترل داخلی", count: 9, amount: 3_800_000_000 },
    { category: "شواهد ناقص", count: 5, amount: 400_000_000 },
  ],
  topRiskVendors: [
    { vendorId: "v-golestan", name: "گلستان پارس", riskScore: 78, amount: 6_800_000_000 },
    { vendorId: "v-arya-service", name: "خدمات فنی آریا", riskScore: 61, amount: 12_400_000_000 },
    { vendorId: "v-parsian-it", name: "پارسیان فناوری", riskScore: 32, amount: 3_200_000_000 },
  ],
  monthlyThroughput: [
    { period: "فروردین", reviewed: 22, flagged: 4 },
    { period: "اردیبهشت", reviewed: 31, flagged: 6 },
    { period: "خرداد", reviewed: 34, flagged: 9 },
    { period: "تیر", reviewed: 41, flagged: 12 },
  ],
};

// ================= Phase 4 mock data =================
import type {
  AppNotification,
  Engagement,
  Integration,
} from "@/types/domain";

export const engagements: Engagement[] = [
  {
    id: "eng-1",
    code: "ENG-1405-07",
    title: "بررسی خریدهای تشریفاتی و تدارکاتی سه‌ماهه دوم",
    scope: "کلیه اسناد خرید مستقیم بالای ۱ میلیارد ریال — واحد تدارکات",
    objective: "ارزیابی رعایت آیین‌نامه معاملات داخلی، صحت شواهد الکترونیکی و ناهنجاری قیمت.",
    status: "InProgress",
    priority: "high",
    leadAuditorId: "u-1",
    teamIds: ["u-1", "u-4"],
    startDate: "۱۴۰۵/۰۴/۰۱",
    endDate: "۱۴۰۵/۰۵/۱۵",
    progress: 62,
    documentIds: ["d-flower-1405", "d-laptop-1405"],
    vendorIds: ["v-golestan", "v-parsian-it"],
    tasks: [
      { id: "t-1", title: "استخراج نمونه اسناد از ERP", done: true, assigneeId: "u-4", dueDate: "۱۴۰۵/۰۴/۰۳" },
      { id: "t-2", title: "اجرای Pipeline انطباق روی نمونه", done: true, assigneeId: "u-1", dueDate: "۱۴۰۵/۰۴/۱۰" },
      { id: "t-3", title: "بررسی یافته‌های Suggested با مدیر", done: false, assigneeId: "u-1", dueDate: "۱۴۰۵/۰۴/۲۵" },
      { id: "t-4", title: "تهیه پیش‌نویس گزارش نهایی", done: false, assigneeId: "u-4", dueDate: "۱۴۰۵/۰۵/۰۵" },
      { id: "t-5", title: "ارائه به کمیته حسابرسی", done: false, dueDate: "۱۴۰۵/۰۵/۱۵" },
    ],
    createdAt: "۱۴۰۵/۰۳/۲۸",
  },
  {
    id: "eng-2",
    code: "ENG-1405-08",
    title: "حسابرسی قراردادهای خدمات پیمانکاری",
    scope: "قراردادهای واحد فنی — تمرکز روی مادهٔ ۳۸ تأمین اجتماعی و مالیات تکلیفی.",
    objective: "اطمینان از دریافت مفاصاحساب بیمه و کسر مالیات تکلیفی.",
    status: "Planned",
    priority: "medium",
    leadAuditorId: "u-1",
    teamIds: ["u-1"],
    startDate: "۱۴۰۵/۰۵/۰۱",
    endDate: "۱۴۰۵/۰۶/۱۵",
    progress: 8,
    documentIds: [],
    vendorIds: ["v-arya-service"],
    tasks: [
      { id: "t-1", title: "تعیین جامعه آماری قراردادها", done: true },
      { id: "t-2", title: "تدوین برنامه نمونه‌گیری", done: false, dueDate: "۱۴۰۵/۰۵/۰۵" },
      { id: "t-3", title: "درخواست مستندات از واحد حقوقی", done: false, dueDate: "۱۴۰۵/۰۵/۱۰" },
    ],
    createdAt: "۱۴۰۵/۰۴/۱۵",
  },
  {
    id: "eng-3",
    code: "ENG-1404-19",
    title: "بازنگری کنترل‌های داخلی موجودی کالا",
    scope: "انبارهای مرکزی — سال مالی ۱۴۰۴.",
    objective: "ارزیابی طراحی و اجرای کنترل‌های موجودی و شمارش پایان دوره.",
    status: "Closed",
    priority: "medium",
    leadAuditorId: "u-1",
    teamIds: ["u-1", "u-5"],
    startDate: "۱۴۰۴/۱۱/۰۱",
    endDate: "۱۴۰۴/۱۲/۲۵",
    progress: 100,
    documentIds: [],
    vendorIds: [],
    tasks: [
      { id: "t-1", title: "شمارش فیزیکی نمونه", done: true },
      { id: "t-2", title: "مغایرت‌گیری با سیستم", done: true },
      { id: "t-3", title: "گزارش نهایی و ارائه به مدیریت", done: true },
    ],
    createdAt: "۱۴۰۴/۱۰/۲۵",
  },
];

export const integrations: Integration[] = [
  {
    id: "int-erp",
    name: "سیستم ERP سازمانی",
    provider: "پارسیان‌سافت — نسخهٔ ۹",
    kind: "erp",
    status: "connected",
    description: "دریافت خودکار اسناد حسابداری، ثبت‌های روزنامه و اطلاعات تأمین‌کنندگان.",
    lastSyncAt: "۱۴۰۵/۰۴/۲۰ ۰۸:۳۰",
    nextSyncAt: "۱۴۰۵/۰۴/۲۰ ۱۴:۳۰",
    itemsSynced: 3421,
    configFields: [
      { key: "endpoint", label: "آدرس سرویس", value: "https://erp.persia.internal/api" },
      { key: "clientId", label: "شناسه کاربر", value: "audit-bot" },
      { key: "secret", label: "کلید محرمانه", masked: true, value: "••••••••" },
    ],
    events: [
      { at: "۱۴۰۵/۰۴/۲۰ ۰۸:۳۰", message: "۱۲۴ سند جدید دریافت شد.", level: "info" },
      { at: "۱۴۰۵/۰۴/۱۹ ۰۸:۳۰", message: "۹۸ سند جدید دریافت شد.", level: "info" },
    ],
  },
  {
    id: "int-taxpayer",
    name: "سامانه مؤدیان",
    provider: "سازمان امور مالیاتی",
    kind: "tax",
    status: "connected",
    description: "استعلام شماره منحصر‌به‌فرد صورتحساب الکترونیکی و اعتبارسنجی خودکار.",
    lastSyncAt: "۱۴۰۵/۰۴/۲۰ ۰۹:۱۰",
    itemsSynced: 812,
    configFields: [
      { key: "companyId", label: "شناسه مؤدی", value: "10101234567" },
      { key: "token", label: "توکن دسترسی", masked: true, value: "••••••••" },
    ],
    events: [
      { at: "۱۴۰۵/۰۴/۱۵ ۱۰:۲۰", message: "استعلام سند AP-1405-0421 — نتیجه: یافت نشد.", level: "warn" },
    ],
  },
  {
    id: "int-bank",
    name: "درگاه اطلاعات بانکی",
    provider: "بانک ملت — سرویس Open API",
    kind: "bank",
    status: "syncing",
    description: "همتاسازی گردش حساب شرکت با اسناد پرداخت.",
    lastSyncAt: "۱۴۰۵/۰۴/۱۹ ۲۳:۰۰",
    itemsSynced: 1567,
    configFields: [
      { key: "accountNo", label: "شماره حساب", value: "IR58-0120-...-4501" },
      { key: "apiKey", label: "کلید API", masked: true, value: "••••••••" },
    ],
    events: [
      { at: "۱۴۰۵/۰۴/۲۰ ۰۹:۰۰", message: "همگام‌سازی روزانه در جریان است.", level: "info" },
    ],
  },
  {
    id: "int-email",
    name: "دریافت اسناد از ایمیل",
    provider: "Microsoft 365 — Shared Mailbox",
    kind: "email",
    status: "error",
    description: "استخراج پیوست‌های ایمیل فاکتور و ارسال به OCR.",
    lastSyncAt: "۱۴۰۵/۰۴/۱۸ ۲۲:۱۰",
    itemsSynced: 78,
    configFields: [
      { key: "mailbox", label: "صندوق پستی", value: "invoices@persia.co" },
      { key: "clientSecret", label: "Client Secret", masked: true, value: "••••••••" },
    ],
    events: [
      { at: "۱۴۰۵/۰۴/۱۹ ۰۶:۰۰", message: "خطای احراز هویت OAuth — نیازمند تجدید توکن.", level: "error" },
    ],
  },
  {
    id: "int-ocr",
    name: "OCR فارسی اسناد",
    provider: "سرویس داخلی — Vision Model",
    kind: "ocr",
    status: "connected",
    description: "استخراج متن از فاکتورهای PDF و تصویری.",
    lastSyncAt: "۱۴۰۵/۰۴/۲۰ ۰۹:۱۵",
    itemsSynced: 421,
    configFields: [
      { key: "endpoint", label: "آدرس سرویس", value: "https://ocr.internal/v1/parse" },
    ],
  },
  {
    id: "int-ad",
    name: "احراز هویت سازمانی",
    provider: "Active Directory (SAML)",
    kind: "identity",
    status: "connected",
    description: "SSO برای ورود حسابرسان و اعمال نقش‌ها.",
    lastSyncAt: "۱۴۰۵/۰۴/۲۰ ۰۸:۰۰",
    configFields: [
      { key: "entityId", label: "Entity ID", value: "didban-audit-sp" },
      { key: "idpUrl", label: "IdP URL", value: "https://sso.persia.internal/saml" },
    ],
  },
  {
    id: "int-s3",
    name: "بایگانی امن اسناد",
    provider: "MinIO — Internal S3",
    kind: "storage",
    status: "disconnected",
    description: "بایگانی نسخهٔ اصلی PDF فاکتورها و شواهد.",
    configFields: [
      { key: "bucket", label: "Bucket", value: "audit-evidence" },
      { key: "accessKey", label: "Access Key", masked: true, value: "" },
      { key: "secretKey", label: "Secret Key", masked: true, value: "" },
    ],
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: "n-1",
    title: "یافتهٔ پرریسک جدید — خرید گل ۲٫۴ م.ت",
    body: "سیستم برای سند AP-1405-0421 یک یافتهٔ Suggested با امتیاز ۸۷ ثبت کرد.",
    level: "critical",
    channels: ["app", "email"],
    createdAt: "۱۴۰۵/۰۴/۲۰ ۰۹:۴۵",
    read: false,
    link: { label: "مشاهدهٔ سند", to: "/app/documents/d-flower-1405" },
    category: "finding",
  },
  {
    id: "n-2",
    title: "خطای اتصال سامانه مؤدیان",
    body: "استعلام صورتحساب الکترونیکی برای سند AP-1405-0421 ناموفق بود؛ توکن نیاز به تجدید دارد.",
    level: "warn",
    channels: ["app", "email"],
    createdAt: "۱۴۰۵/۰۴/۲۰ ۰۹:۱۲",
    read: false,
    link: { label: "بررسی یکپارچه‌سازی", to: "/app/integrations" },
    category: "integration",
  },
  {
    id: "n-3",
    title: "وظیفه جدید در مأموریت ENG-1405-07",
    body: "بررسی یافته‌های Suggested با مدیر — سررسید ۱۴۰۵/۰۴/۲۵.",
    level: "info",
    channels: ["app"],
    createdAt: "۱۴۰۵/۰۴/۱۹ ۱۸:۰۰",
    read: false,
    link: { label: "مشاهدهٔ مأموریت", to: "/app/engagements/eng-1" },
    category: "engagement",
  },
  {
    id: "n-4",
    title: "خلاصه روزانه — ۲۰ تیر",
    body: "۳ یافتهٔ جدید، ۲ سند پرریسک، ۱ خطای یکپارچه‌سازی.",
    level: "info",
    channels: ["email"],
    createdAt: "۱۴۰۵/۰۴/۲۰ ۰۷:۰۰",
    read: true,
    category: "system",
  },
  {
    id: "n-5",
    title: "تأمین‌کننده در فهرست هشدار",
    body: "«گلستان پارس» به دلیل ارتباط سهامداری با کارمند تدارکات به Watchlist اضافه شد.",
    level: "warn",
    channels: ["app"],
    createdAt: "۱۴۰۵/۰۴/۱۸ ۱۴:۳۰",
    read: true,
    link: { label: "پروفایل تأمین‌کننده", to: "/app/vendors/v-golestan" },
    category: "vendor",
  },
];
