/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppVendorsIndexRouteImport } from './routes/app/vendors/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppRulesIndexRouteImport } from './routes/app/rules/index'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppMonitoringIndexRouteImport } from './routes/app/monitoring/index'
import { Route as AppKnowledgeIndexRouteImport } from './routes/app/knowledge/index'
import { Route as AppIntegrationsIndexRouteImport } from './routes/app/integrations/index'
import { Route as AppInboxIndexRouteImport } from './routes/app/inbox/index'
import { Route as AppFindingsIndexRouteImport } from './routes/app/findings/index'
import { Route as AppExecutiveIndexRouteImport } from './routes/app/executive/index'
import { Route as AppEngagementsIndexRouteImport } from './routes/app/engagements/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppAuditRunsIndexRouteImport } from './routes/app/audit-runs/index'
import { Route as AppAssistantIndexRouteImport } from './routes/app/assistant/index'
import { Route as AppVendorsIdRouteImport } from './routes/app/vendors/$id'
import { Route as AppFindingsIdRouteImport } from './routes/app/findings/$id'
import { Route as AppEngagementsIdRouteImport } from './routes/app/engagements/$id'
import { Route as AppDocumentsIdRouteImport } from './routes/app/documents/$id'
import { Route as AppAuditRunsNewRouteImport } from './routes/app/audit-runs/new'
import { Route as AppAuditRunsIdRouteImport } from './routes/app/audit-runs/$id'
import { Route as AppAuditRunsIdReportRouteImport } from './routes/app/audit-runs/$id.report'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRulesIndexRoute = AppRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMonitoringIndexRoute = AppMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgeIndexRoute = AppKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFindingsIndexRoute = AppFindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExecutiveIndexRoute = AppExecutiveIndexRouteImport.update({
  id: '/executive/',
  path: '/executive/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEngagementsIndexRoute = AppEngagementsIndexRouteImport.update({
  id: '/engagements/',
  path: '/engagements/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRunsIndexRoute = AppAuditRunsIndexRouteImport.update({
  id: '/audit-runs/',
  path: '/audit-runs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssistantIndexRoute = AppAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFindingsIdRoute = AppFindingsIdRouteImport.update({
  id: '/findings/$id',
  path: '/findings/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEngagementsIdRoute = AppEngagementsIdRouteImport.update({
  id: '/engagements/$id',
  path: '/engagements/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRunsNewRoute = AppAuditRunsNewRouteImport.update({
  id: '/audit-runs/new',
  path: '/audit-runs/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRunsIdRoute = AppAuditRunsIdRouteImport.update({
  id: '/audit-runs/$id',
  path: '/audit-runs/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRunsIdReportRoute = AppAuditRunsIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppAuditRunsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/audit-runs/$id': typeof AppAuditRunsIdRouteWithChildren
  '/app/audit-runs/new': typeof AppAuditRunsNewRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/engagements/$id': typeof AppEngagementsIdRoute
  '/app/findings/$id': typeof AppFindingsIdRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/app/assistant/': typeof AppAssistantIndexRoute
  '/app/audit-runs/': typeof AppAuditRunsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/engagements/': typeof AppEngagementsIndexRoute
  '/app/executive/': typeof AppExecutiveIndexRoute
  '/app/findings/': typeof AppFindingsIndexRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/knowledge/': typeof AppKnowledgeIndexRoute
  '/app/monitoring/': typeof AppMonitoringIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/rules/': typeof AppRulesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/vendors/': typeof AppVendorsIndexRoute
  '/app/audit-runs/$id/report': typeof AppAuditRunsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/audit-runs/$id': typeof AppAuditRunsIdRouteWithChildren
  '/app/audit-runs/new': typeof AppAuditRunsNewRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/engagements/$id': typeof AppEngagementsIdRoute
  '/app/findings/$id': typeof AppFindingsIdRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/app/assistant': typeof AppAssistantIndexRoute
  '/app/audit-runs': typeof AppAuditRunsIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/engagements': typeof AppEngagementsIndexRoute
  '/app/executive': typeof AppExecutiveIndexRoute
  '/app/findings': typeof AppFindingsIndexRoute
  '/app/inbox': typeof AppInboxIndexRoute
  '/app/integrations': typeof AppIntegrationsIndexRoute
  '/app/knowledge': typeof AppKnowledgeIndexRoute
  '/app/monitoring': typeof AppMonitoringIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/rules': typeof AppRulesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/vendors': typeof AppVendorsIndexRoute
  '/app/audit-runs/$id/report': typeof AppAuditRunsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/audit-runs/$id': typeof AppAuditRunsIdRouteWithChildren
  '/app/audit-runs/new': typeof AppAuditRunsNewRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/engagements/$id': typeof AppEngagementsIdRoute
  '/app/findings/$id': typeof AppFindingsIdRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/app/assistant/': typeof AppAssistantIndexRoute
  '/app/audit-runs/': typeof AppAuditRunsIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/engagements/': typeof AppEngagementsIndexRoute
  '/app/executive/': typeof AppExecutiveIndexRoute
  '/app/findings/': typeof AppFindingsIndexRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/knowledge/': typeof AppKnowledgeIndexRoute
  '/app/monitoring/': typeof AppMonitoringIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/rules/': typeof AppRulesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/vendors/': typeof AppVendorsIndexRoute
  '/app/audit-runs/$id/report': typeof AppAuditRunsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/audit-runs/$id'
    | '/app/audit-runs/new'
    | '/app/documents/$id'
    | '/app/engagements/$id'
    | '/app/findings/$id'
    | '/app/vendors/$id'
    | '/app/assistant/'
    | '/app/audit-runs/'
    | '/app/documents/'
    | '/app/engagements/'
    | '/app/executive/'
    | '/app/findings/'
    | '/app/inbox/'
    | '/app/integrations/'
    | '/app/knowledge/'
    | '/app/monitoring/'
    | '/app/reports/'
    | '/app/rules/'
    | '/app/settings/'
    | '/app/vendors/'
    | '/app/audit-runs/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/audit-runs/$id'
    | '/app/audit-runs/new'
    | '/app/documents/$id'
    | '/app/engagements/$id'
    | '/app/findings/$id'
    | '/app/vendors/$id'
    | '/app/assistant'
    | '/app/audit-runs'
    | '/app/documents'
    | '/app/engagements'
    | '/app/executive'
    | '/app/findings'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/monitoring'
    | '/app/reports'
    | '/app/rules'
    | '/app/settings'
    | '/app/vendors'
    | '/app/audit-runs/$id/report'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/audit-runs/$id'
    | '/app/audit-runs/new'
    | '/app/documents/$id'
    | '/app/engagements/$id'
    | '/app/findings/$id'
    | '/app/vendors/$id'
    | '/app/assistant/'
    | '/app/audit-runs/'
    | '/app/documents/'
    | '/app/engagements/'
    | '/app/executive/'
    | '/app/findings/'
    | '/app/inbox/'
    | '/app/integrations/'
    | '/app/knowledge/'
    | '/app/monitoring/'
    | '/app/reports/'
    | '/app/rules/'
    | '/app/settings/'
    | '/app/vendors/'
    | '/app/audit-runs/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendors/': {
      id: '/app/vendors/'
      path: '/vendors'
      fullPath: '/app/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rules/': {
      id: '/app/rules/'
      path: '/rules'
      fullPath: '/app/rules/'
      preLoaderRoute: typeof AppRulesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/monitoring/': {
      id: '/app/monitoring/'
      path: '/monitoring'
      fullPath: '/app/monitoring/'
      preLoaderRoute: typeof AppMonitoringIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/knowledge/': {
      id: '/app/knowledge/'
      path: '/knowledge'
      fullPath: '/app/knowledge/'
      preLoaderRoute: typeof AppKnowledgeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/integrations/': {
      id: '/app/integrations/'
      path: '/integrations'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inbox/': {
      id: '/app/inbox/'
      path: '/inbox'
      fullPath: '/app/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/findings/': {
      id: '/app/findings/'
      path: '/findings'
      fullPath: '/app/findings/'
      preLoaderRoute: typeof AppFindingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/executive/': {
      id: '/app/executive/'
      path: '/executive'
      fullPath: '/app/executive/'
      preLoaderRoute: typeof AppExecutiveIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/engagements/': {
      id: '/app/engagements/'
      path: '/engagements'
      fullPath: '/app/engagements/'
      preLoaderRoute: typeof AppEngagementsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit-runs/': {
      id: '/app/audit-runs/'
      path: '/audit-runs'
      fullPath: '/app/audit-runs/'
      preLoaderRoute: typeof AppAuditRunsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assistant/': {
      id: '/app/assistant/'
      path: '/assistant'
      fullPath: '/app/assistant/'
      preLoaderRoute: typeof AppAssistantIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendors/$id': {
      id: '/app/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/app/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/findings/$id': {
      id: '/app/findings/$id'
      path: '/findings/$id'
      fullPath: '/app/findings/$id'
      preLoaderRoute: typeof AppFindingsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/engagements/$id': {
      id: '/app/engagements/$id'
      path: '/engagements/$id'
      fullPath: '/app/engagements/$id'
      preLoaderRoute: typeof AppEngagementsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents/$id': {
      id: '/app/documents/$id'
      path: '/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit-runs/new': {
      id: '/app/audit-runs/new'
      path: '/audit-runs/new'
      fullPath: '/app/audit-runs/new'
      preLoaderRoute: typeof AppAuditRunsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit-runs/$id': {
      id: '/app/audit-runs/$id'
      path: '/audit-runs/$id'
      fullPath: '/app/audit-runs/$id'
      preLoaderRoute: typeof AppAuditRunsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit-runs/$id/report': {
      id: '/app/audit-runs/$id/report'
      path: '/report'
      fullPath: '/app/audit-runs/$id/report'
      preLoaderRoute: typeof AppAuditRunsIdReportRouteImport
      parentRoute: typeof AppAuditRunsIdRoute
    }
  }
}

interface AppAuditRunsIdRouteChildren {
  AppAuditRunsIdReportRoute: typeof AppAuditRunsIdReportRoute
}

const AppAuditRunsIdRouteChildren: AppAuditRunsIdRouteChildren = {
  AppAuditRunsIdReportRoute: AppAuditRunsIdReportRoute,
}

const AppAuditRunsIdRouteWithChildren = AppAuditRunsIdRoute._addFileChildren(
  AppAuditRunsIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAuditRunsIdRoute: typeof AppAuditRunsIdRouteWithChildren
  AppAuditRunsNewRoute: typeof AppAuditRunsNewRoute
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
  AppEngagementsIdRoute: typeof AppEngagementsIdRoute
  AppFindingsIdRoute: typeof AppFindingsIdRoute
  AppVendorsIdRoute: typeof AppVendorsIdRoute
  AppAssistantIndexRoute: typeof AppAssistantIndexRoute
  AppAuditRunsIndexRoute: typeof AppAuditRunsIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppEngagementsIndexRoute: typeof AppEngagementsIndexRoute
  AppExecutiveIndexRoute: typeof AppExecutiveIndexRoute
  AppFindingsIndexRoute: typeof AppFindingsIndexRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppKnowledgeIndexRoute: typeof AppKnowledgeIndexRoute
  AppMonitoringIndexRoute: typeof AppMonitoringIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppRulesIndexRoute: typeof AppRulesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAuditRunsIdRoute: AppAuditRunsIdRouteWithChildren,
  AppAuditRunsNewRoute: AppAuditRunsNewRoute,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
  AppEngagementsIdRoute: AppEngagementsIdRoute,
  AppFindingsIdRoute: AppFindingsIdRoute,
  AppVendorsIdRoute: AppVendorsIdRoute,
  AppAssistantIndexRoute: AppAssistantIndexRoute,
  AppAuditRunsIndexRoute: AppAuditRunsIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppEngagementsIndexRoute: AppEngagementsIndexRoute,
  AppExecutiveIndexRoute: AppExecutiveIndexRoute,
  AppFindingsIndexRoute: AppFindingsIndexRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppKnowledgeIndexRoute: AppKnowledgeIndexRoute,
  AppMonitoringIndexRoute: AppMonitoringIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppRulesIndexRoute: AppRulesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
